package com.airmap.airmapsdk.models;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

@SuppressWarnings("ALL")
public final class Telemetry {
    private Telemetry() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface SecretMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SecretMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required float latitude = 1;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        boolean hasLatitude();
        /**
         * <code>required float latitude = 1;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        float getLatitude();

        /**
         * <code>required float longitude = 2;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        boolean hasLongitude();
        /**
         * <code>required float longitude = 2;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        float getLongitude();

        /**
         * <code>required sint32 altitude = 3;</code>
         *
         * <pre>
         * Altitude is always in Meters
         * </pre>
         */
        boolean hasAltitude();
        /**
         * <code>required sint32 altitude = 3;</code>
         *
         * <pre>
         * Altitude is always in Meters
         * </pre>
         */
        int getAltitude();

        /**
         * <code>required uint64 timestamp = 4;</code>
         *
         * <pre>
         * Seconds since epoc UTC
         * </pre>
         */
        boolean hasTimestamp();
        /**
         * <code>required uint64 timestamp = 4;</code>
         *
         * <pre>
         * Seconds since epoc UTC
         * </pre>
         */
        long getTimestamp();

        /**
         * <code>optional uint32 ground_speed_ms = 5;</code>
         *
         * <pre>
         * Ground speen in meters/second.
         * </pre>
         */
        boolean hasGroundSpeedMs();
        /**
         * <code>optional uint32 ground_speed_ms = 5;</code>
         *
         * <pre>
         * Ground speen in meters/second.
         * </pre>
         */
        int getGroundSpeedMs();

        /**
         * <code>optional uint32 true_heading = 6;</code>
         *
         * <pre>
         * Heading relative to True North
         * </pre>
         */
        boolean hasTrueHeading();
        /**
         * <code>optional uint32 true_heading = 6;</code>
         *
         * <pre>
         * Heading relative to True North
         * </pre>
         */
        int getTrueHeading();

        /**
         * <code>optional float baro = 7;</code>
         *
         * <pre>
         * Barometric reading
         * </pre>
         */
        boolean hasBaro();
        /**
         * <code>optional float baro = 7;</code>
         *
         * <pre>
         * Barometric reading
         * </pre>
         */
        float getBaro();
    }
    /**
     * Protobuf type {@code SecretMessage}
     */
    public static final class SecretMessage extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:SecretMessage)
            SecretMessageOrBuilder {
        // Use SecretMessage.newBuilder() to construct.
        private SecretMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private SecretMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final SecretMessage defaultInstance;
        public static SecretMessage getDefaultInstance() {
            return defaultInstance;
        }

        public SecretMessage getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SecretMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 13: {
                            bitField0_ |= 0x00000001;
                            latitude_ = input.readFloat();
                            break;
                        }
                        case 21: {
                            bitField0_ |= 0x00000002;
                            longitude_ = input.readFloat();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            altitude_ = input.readSInt32();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            timestamp_ = input.readUInt64();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            groundSpeedMs_ = input.readUInt32();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            trueHeading_ = input.readUInt32();
                            break;
                        }
                        case 61: {
                            bitField0_ |= 0x00000040;
                            baro_ = input.readFloat();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Telemetry.internal_static_SecretMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Telemetry.internal_static_SecretMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Telemetry.SecretMessage.class, Telemetry.SecretMessage.Builder.class);
        }

        public static com.google.protobuf.Parser<SecretMessage> PARSER =
                new com.google.protobuf.AbstractParser<SecretMessage>() {
                    public SecretMessage parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new SecretMessage(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<SecretMessage> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int LATITUDE_FIELD_NUMBER = 1;
        private float latitude_;
        /**
         * <code>required float latitude = 1;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        public boolean hasLatitude() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required float latitude = 1;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        public float getLatitude() {
            return latitude_;
        }

        public static final int LONGITUDE_FIELD_NUMBER = 2;
        private float longitude_;
        /**
         * <code>required float longitude = 2;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        public boolean hasLongitude() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required float longitude = 2;</code>
         *
         * <pre>
         * Decimal place requirement: 7 decimal places.
         * </pre>
         */
        public float getLongitude() {
            return longitude_;
        }

        public static final int ALTITUDE_FIELD_NUMBER = 3;
        private int altitude_;
        /**
         * <code>required sint32 altitude = 3;</code>
         *
         * <pre>
         * Altitude is always in Meters
         * </pre>
         */
        public boolean hasAltitude() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required sint32 altitude = 3;</code>
         *
         * <pre>
         * Altitude is always in Meters
         * </pre>
         */
        public int getAltitude() {
            return altitude_;
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 4;
        private long timestamp_;
        /**
         * <code>required uint64 timestamp = 4;</code>
         *
         * <pre>
         * Seconds since epoc UTC
         * </pre>
         */
        public boolean hasTimestamp() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required uint64 timestamp = 4;</code>
         *
         * <pre>
         * Seconds since epoc UTC
         * </pre>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        public static final int GROUND_SPEED_MS_FIELD_NUMBER = 5;
        private int groundSpeedMs_;
        /**
         * <code>optional uint32 ground_speed_ms = 5;</code>
         *
         * <pre>
         * Ground speen in meters/second.
         * </pre>
         */
        public boolean hasGroundSpeedMs() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional uint32 ground_speed_ms = 5;</code>
         *
         * <pre>
         * Ground speen in meters/second.
         * </pre>
         */
        public int getGroundSpeedMs() {
            return groundSpeedMs_;
        }

        public static final int TRUE_HEADING_FIELD_NUMBER = 6;
        private int trueHeading_;
        /**
         * <code>optional uint32 true_heading = 6;</code>
         *
         * <pre>
         * Heading relative to True North
         * </pre>
         */
        public boolean hasTrueHeading() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional uint32 true_heading = 6;</code>
         *
         * <pre>
         * Heading relative to True North
         * </pre>
         */
        public int getTrueHeading() {
            return trueHeading_;
        }

        public static final int BARO_FIELD_NUMBER = 7;
        private float baro_;
        /**
         * <code>optional float baro = 7;</code>
         *
         * <pre>
         * Barometric reading
         * </pre>
         */
        public boolean hasBaro() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional float baro = 7;</code>
         *
         * <pre>
         * Barometric reading
         * </pre>
         */
        public float getBaro() {
            return baro_;
        }

        private void initFields() {
            latitude_ = 0F;
            longitude_ = 0F;
            altitude_ = 0;
            timestamp_ = 0L;
            groundSpeedMs_ = 0;
            trueHeading_ = 0;
            baro_ = 0F;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasLatitude()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasLongitude()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAltitude()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTimestamp()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeFloat(1, latitude_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeFloat(2, longitude_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeSInt32(3, altitude_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeUInt64(4, timestamp_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeUInt32(5, groundSpeedMs_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeUInt32(6, trueHeading_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeFloat(7, baro_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(1, latitude_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(2, longitude_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(3, altitude_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, timestamp_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, groundSpeedMs_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(6, trueHeading_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(7, baro_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Telemetry.SecretMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Telemetry.SecretMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Telemetry.SecretMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Telemetry.SecretMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Telemetry.SecretMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Telemetry.SecretMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static Telemetry.SecretMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static Telemetry.SecretMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static Telemetry.SecretMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Telemetry.SecretMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(Telemetry.SecretMessage prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code SecretMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:SecretMessage)
                Telemetry.SecretMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Telemetry.internal_static_SecretMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Telemetry.internal_static_SecretMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Telemetry.SecretMessage.class, Telemetry.SecretMessage.Builder.class);
            }

            // Construct using Telemetry.SecretMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                latitude_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000001);
                longitude_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000002);
                altitude_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                timestamp_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000008);
                groundSpeedMs_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                trueHeading_ = 0;
                bitField0_ = (bitField0_ & ~0x00000020);
                baro_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000040);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Telemetry.internal_static_SecretMessage_descriptor;
            }

            public Telemetry.SecretMessage getDefaultInstanceForType() {
                return Telemetry.SecretMessage.getDefaultInstance();
            }

            public Telemetry.SecretMessage build() {
                Telemetry.SecretMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Telemetry.SecretMessage buildPartial() {
                Telemetry.SecretMessage result = new Telemetry.SecretMessage(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.latitude_ = latitude_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.longitude_ = longitude_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.altitude_ = altitude_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.timestamp_ = timestamp_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.groundSpeedMs_ = groundSpeedMs_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.trueHeading_ = trueHeading_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.baro_ = baro_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Telemetry.SecretMessage) {
                    return mergeFrom((Telemetry.SecretMessage)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Telemetry.SecretMessage other) {
                if (other == Telemetry.SecretMessage.getDefaultInstance()) return this;
                if (other.hasLatitude()) {
                    setLatitude(other.getLatitude());
                }
                if (other.hasLongitude()) {
                    setLongitude(other.getLongitude());
                }
                if (other.hasAltitude()) {
                    setAltitude(other.getAltitude());
                }
                if (other.hasTimestamp()) {
                    setTimestamp(other.getTimestamp());
                }
                if (other.hasGroundSpeedMs()) {
                    setGroundSpeedMs(other.getGroundSpeedMs());
                }
                if (other.hasTrueHeading()) {
                    setTrueHeading(other.getTrueHeading());
                }
                if (other.hasBaro()) {
                    setBaro(other.getBaro());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasLatitude()) {

                    return false;
                }
                if (!hasLongitude()) {

                    return false;
                }
                if (!hasAltitude()) {

                    return false;
                }
                if (!hasTimestamp()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Telemetry.SecretMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Telemetry.SecretMessage) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private float latitude_ ;
            /**
             * <code>required float latitude = 1;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public boolean hasLatitude() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required float latitude = 1;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public float getLatitude() {
                return latitude_;
            }
            /**
             * <code>required float latitude = 1;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public Builder setLatitude(float value) {
                bitField0_ |= 0x00000001;
                latitude_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required float latitude = 1;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public Builder clearLatitude() {
                bitField0_ = (bitField0_ & ~0x00000001);
                latitude_ = 0F;
                onChanged();
                return this;
            }

            private float longitude_ ;
            /**
             * <code>required float longitude = 2;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public boolean hasLongitude() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required float longitude = 2;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public float getLongitude() {
                return longitude_;
            }
            /**
             * <code>required float longitude = 2;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public Builder setLongitude(float value) {
                bitField0_ |= 0x00000002;
                longitude_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required float longitude = 2;</code>
             *
             * <pre>
             * Decimal place requirement: 7 decimal places.
             * </pre>
             */
            public Builder clearLongitude() {
                bitField0_ = (bitField0_ & ~0x00000002);
                longitude_ = 0F;
                onChanged();
                return this;
            }

            private int altitude_ ;
            /**
             * <code>required sint32 altitude = 3;</code>
             *
             * <pre>
             * Altitude is always in Meters
             * </pre>
             */
            public boolean hasAltitude() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>required sint32 altitude = 3;</code>
             *
             * <pre>
             * Altitude is always in Meters
             * </pre>
             */
            public int getAltitude() {
                return altitude_;
            }
            /**
             * <code>required sint32 altitude = 3;</code>
             *
             * <pre>
             * Altitude is always in Meters
             * </pre>
             */
            public Builder setAltitude(int value) {
                bitField0_ |= 0x00000004;
                altitude_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required sint32 altitude = 3;</code>
             *
             * <pre>
             * Altitude is always in Meters
             * </pre>
             */
            public Builder clearAltitude() {
                bitField0_ = (bitField0_ & ~0x00000004);
                altitude_ = 0;
                onChanged();
                return this;
            }

            private long timestamp_ ;
            /**
             * <code>required uint64 timestamp = 4;</code>
             *
             * <pre>
             * Seconds since epoc UTC
             * </pre>
             */
            public boolean hasTimestamp() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            /**
             * <code>required uint64 timestamp = 4;</code>
             *
             * <pre>
             * Seconds since epoc UTC
             * </pre>
             */
            public long getTimestamp() {
                return timestamp_;
            }
            /**
             * <code>required uint64 timestamp = 4;</code>
             *
             * <pre>
             * Seconds since epoc UTC
             * </pre>
             */
            public Builder setTimestamp(long value) {
                bitField0_ |= 0x00000008;
                timestamp_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required uint64 timestamp = 4;</code>
             *
             * <pre>
             * Seconds since epoc UTC
             * </pre>
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000008);
                timestamp_ = 0L;
                onChanged();
                return this;
            }

            private int groundSpeedMs_ ;
            /**
             * <code>optional uint32 ground_speed_ms = 5;</code>
             *
             * <pre>
             * Ground speen in meters/second.
             * </pre>
             */
            public boolean hasGroundSpeedMs() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }
            /**
             * <code>optional uint32 ground_speed_ms = 5;</code>
             *
             * <pre>
             * Ground speen in meters/second.
             * </pre>
             */
            public int getGroundSpeedMs() {
                return groundSpeedMs_;
            }
            /**
             * <code>optional uint32 ground_speed_ms = 5;</code>
             *
             * <pre>
             * Ground speen in meters/second.
             * </pre>
             */
            public Builder setGroundSpeedMs(int value) {
                bitField0_ |= 0x00000010;
                groundSpeedMs_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional uint32 ground_speed_ms = 5;</code>
             *
             * <pre>
             * Ground speen in meters/second.
             * </pre>
             */
            public Builder clearGroundSpeedMs() {
                bitField0_ = (bitField0_ & ~0x00000010);
                groundSpeedMs_ = 0;
                onChanged();
                return this;
            }

            private int trueHeading_ ;
            /**
             * <code>optional uint32 true_heading = 6;</code>
             *
             * <pre>
             * Heading relative to True North
             * </pre>
             */
            public boolean hasTrueHeading() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }
            /**
             * <code>optional uint32 true_heading = 6;</code>
             *
             * <pre>
             * Heading relative to True North
             * </pre>
             */
            public int getTrueHeading() {
                return trueHeading_;
            }
            /**
             * <code>optional uint32 true_heading = 6;</code>
             *
             * <pre>
             * Heading relative to True North
             * </pre>
             */
            public Builder setTrueHeading(int value) {
                bitField0_ |= 0x00000020;
                trueHeading_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional uint32 true_heading = 6;</code>
             *
             * <pre>
             * Heading relative to True North
             * </pre>
             */
            public Builder clearTrueHeading() {
                bitField0_ = (bitField0_ & ~0x00000020);
                trueHeading_ = 0;
                onChanged();
                return this;
            }

            private float baro_ ;
            /**
             * <code>optional float baro = 7;</code>
             *
             * <pre>
             * Barometric reading
             * </pre>
             */
            public boolean hasBaro() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }
            /**
             * <code>optional float baro = 7;</code>
             *
             * <pre>
             * Barometric reading
             * </pre>
             */
            public float getBaro() {
                return baro_;
            }
            /**
             * <code>optional float baro = 7;</code>
             *
             * <pre>
             * Barometric reading
             * </pre>
             */
            public Builder setBaro(float value) {
                bitField0_ |= 0x00000040;
                baro_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional float baro = 7;</code>
             *
             * <pre>
             * Barometric reading
             * </pre>
             */
            public Builder clearBaro() {
                bitField0_ = (bitField0_ & ~0x00000040);
                baro_ = 0F;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:SecretMessage)
        }

        static {
            defaultInstance = new SecretMessage(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:SecretMessage)
    }

    public interface OpenMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:OpenMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string flight_id = 1;</code>
         */
        boolean hasFlightId();
        /**
         * <code>required string flight_id = 1;</code>
         */
        java.lang.String getFlightId();
        /**
         * <code>required string flight_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getFlightIdBytes();

        /**
         * <code>required bytes iv = 2;</code>
         */
        boolean hasIv();
        /**
         * <code>required bytes iv = 2;</code>
         */
        com.google.protobuf.ByteString getIv();

        /**
         * <code>required bytes payload = 3;</code>
         */
        boolean hasPayload();
        /**
         * <code>required bytes payload = 3;</code>
         */
        com.google.protobuf.ByteString getPayload();
    }
    /**
     * Protobuf type {@code OpenMessage}
     */
    public static final class OpenMessage extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:OpenMessage)
            OpenMessageOrBuilder {
        // Use OpenMessage.newBuilder() to construct.
        private OpenMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private OpenMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final OpenMessage defaultInstance;
        public static OpenMessage getDefaultInstance() {
            return defaultInstance;
        }

        public OpenMessage getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private OpenMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            flightId_ = bs;
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            iv_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            payload_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Telemetry.internal_static_OpenMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Telemetry.internal_static_OpenMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Telemetry.OpenMessage.class, Telemetry.OpenMessage.Builder.class);
        }

        public static com.google.protobuf.Parser<OpenMessage> PARSER =
                new com.google.protobuf.AbstractParser<OpenMessage>() {
                    public OpenMessage parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new OpenMessage(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<OpenMessage> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int FLIGHT_ID_FIELD_NUMBER = 1;
        private java.lang.Object flightId_;
        /**
         * <code>required string flight_id = 1;</code>
         */
        public boolean hasFlightId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string flight_id = 1;</code>
         */
        public java.lang.String getFlightId() {
            java.lang.Object ref = flightId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    flightId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string flight_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getFlightIdBytes() {
            java.lang.Object ref = flightId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                flightId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int IV_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString iv_;
        /**
         * <code>required bytes iv = 2;</code>
         */
        public boolean hasIv() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes iv = 2;</code>
         */
        public com.google.protobuf.ByteString getIv() {
            return iv_;
        }

        public static final int PAYLOAD_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString payload_;
        /**
         * <code>required bytes payload = 3;</code>
         */
        public boolean hasPayload() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bytes payload = 3;</code>
         */
        public com.google.protobuf.ByteString getPayload() {
            return payload_;
        }

        private void initFields() {
            flightId_ = "";
            iv_ = com.google.protobuf.ByteString.EMPTY;
            payload_ = com.google.protobuf.ByteString.EMPTY;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasFlightId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasIv()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasPayload()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getFlightIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, iv_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, payload_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getFlightIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, iv_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, payload_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Telemetry.OpenMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Telemetry.OpenMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Telemetry.OpenMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Telemetry.OpenMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Telemetry.OpenMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Telemetry.OpenMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static Telemetry.OpenMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static Telemetry.OpenMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static Telemetry.OpenMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Telemetry.OpenMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(Telemetry.OpenMessage prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code OpenMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:OpenMessage)
                Telemetry.OpenMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Telemetry.internal_static_OpenMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Telemetry.internal_static_OpenMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Telemetry.OpenMessage.class, Telemetry.OpenMessage.Builder.class);
            }

            // Construct using Telemetry.OpenMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                flightId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                iv_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                payload_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Telemetry.internal_static_OpenMessage_descriptor;
            }

            public Telemetry.OpenMessage getDefaultInstanceForType() {
                return Telemetry.OpenMessage.getDefaultInstance();
            }

            public Telemetry.OpenMessage build() {
                Telemetry.OpenMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Telemetry.OpenMessage buildPartial() {
                Telemetry.OpenMessage result = new Telemetry.OpenMessage(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.flightId_ = flightId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.iv_ = iv_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.payload_ = payload_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Telemetry.OpenMessage) {
                    return mergeFrom((Telemetry.OpenMessage)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Telemetry.OpenMessage other) {
                if (other == Telemetry.OpenMessage.getDefaultInstance()) return this;
                if (other.hasFlightId()) {
                    bitField0_ |= 0x00000001;
                    flightId_ = other.flightId_;
                    onChanged();
                }
                if (other.hasIv()) {
                    setIv(other.getIv());
                }
                if (other.hasPayload()) {
                    setPayload(other.getPayload());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasFlightId()) {

                    return false;
                }
                if (!hasIv()) {

                    return false;
                }
                if (!hasPayload()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Telemetry.OpenMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Telemetry.OpenMessage) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object flightId_ = "";
            /**
             * <code>required string flight_id = 1;</code>
             */
            public boolean hasFlightId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required string flight_id = 1;</code>
             */
            public java.lang.String getFlightId() {
                java.lang.Object ref = flightId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        flightId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string flight_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getFlightIdBytes() {
                java.lang.Object ref = flightId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    flightId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string flight_id = 1;</code>
             */
            public Builder setFlightId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                flightId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string flight_id = 1;</code>
             */
            public Builder clearFlightId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                flightId_ = getDefaultInstance().getFlightId();
                onChanged();
                return this;
            }
            /**
             * <code>required string flight_id = 1;</code>
             */
            public Builder setFlightIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                flightId_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>required bytes iv = 2;</code>
             */
            public boolean hasIv() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required bytes iv = 2;</code>
             */
            public com.google.protobuf.ByteString getIv() {
                return iv_;
            }
            /**
             * <code>required bytes iv = 2;</code>
             */
            public Builder setIv(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                iv_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required bytes iv = 2;</code>
             */
            public Builder clearIv() {
                bitField0_ = (bitField0_ & ~0x00000002);
                iv_ = getDefaultInstance().getIv();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>required bytes payload = 3;</code>
             */
            public boolean hasPayload() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>required bytes payload = 3;</code>
             */
            public com.google.protobuf.ByteString getPayload() {
                return payload_;
            }
            /**
             * <code>required bytes payload = 3;</code>
             */
            public Builder setPayload(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                payload_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required bytes payload = 3;</code>
             */
            public Builder clearPayload() {
                bitField0_ = (bitField0_ & ~0x00000004);
                payload_ = getDefaultInstance().getPayload();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:OpenMessage)
        }

        static {
            defaultInstance = new OpenMessage(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:OpenMessage)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SecretMessage_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_SecretMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_OpenMessage_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_OpenMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\017telemetry.proto\"\226\001\n\rSecretMessage\022\020\n\010l" +
                        "atitude\030\001 \002(\002\022\021\n\tlongitude\030\002 \002(\002\022\020\n\010alti" +
                        "tude\030\003 \002(\021\022\021\n\ttimestamp\030\004 \002(\004\022\027\n\017ground_" +
                        "speed_ms\030\005 \001(\r\022\024\n\014true_heading\030\006 \001(\r\022\014\n\004" +
                        "baro\030\007 \001(\002\"=\n\013OpenMessage\022\021\n\tflight_id\030\001" +
                        " \002(\t\022\n\n\002iv\030\002 \002(\014\022\017\n\007payload\030\003 \002(\014"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SecretMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SecretMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_SecretMessage_descriptor,
                new java.lang.String[] { "Latitude", "Longitude", "Altitude", "Timestamp", "GroundSpeedMs", "TrueHeading", "Baro", });
        internal_static_OpenMessage_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_OpenMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_OpenMessage_descriptor,
                new java.lang.String[] { "FlightId", "Iv", "Payload", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
